name: expandfont
version: '1.0'
main: me.redsnickdev.expandfont.Expandfont
description: 'Plugin Created By Chest Solution Organization'
api-version: '1.20'
hard-depend: [PlaceholderAPI]
author: 'Chest Solutions'
website: https://chest-solutions.github.io

commands:
  expandfont:
    description: Test the expandfont placeholder
    usage: /expandfont <font> <placeholder>
